### ISSUE TITLE
Issue with Whisker Length Calculation

### ISSUE THREAD

**Issue by gkemp94** [datavisyn/chartjs-chart-box-and-violin-plot#23]
Most statistics books define the whisker max/min as 
```
MAX = Q3 + IQR*1.5
MIN = Q1 - IQR*1.5
```
Is there a reason this library dictates it as?
![image](https://user-images.githubusercontent.com/24573792/49454385-f334f500-f7dc-11e8-90bf-b678ae162efb.png)

If not can we change this to be 1.5 or have an option to default to either 1.5, 1, or use whatever value we give as the max.

**Comment by sgratzl** [comment]
Actually in the latest version: 

https://github.com/datavisyn/chartjs-chart-box-and-violin-plot/blob/15a2b69a6a2646fb0c7eac54f396b93b11cdd214/src/data.js#L9-L37

given an array of sorted values `arr` the lower whisker is computed as the value of the first element in the sorted array that is bigger than `Q1 - IQR * 1.5`. The upper whisker is the value of the last element that is smaller than `Q3 + IQR * 1.5` accordingly. Thus, the lower whisker is at least the minimal value of the array if `Q1 - IQR * 1.5 < min` since the minimal value represents the first element in the array. I think this implementation is pretty standard similar how R is computing boxplots. 

However, if you wanna customize it you have the option to provide the already computed boxplots statistics to the plugin instead of the plain array. See https://github.com/datavisyn/chartjs-chart-box-and-violin-plot#data-structure.

**Comment by gkemp94** [comment]
Hi @sgratzl, 
Thanks for you reply. What I'm actually doing is sending in those pre-calculated boxplot statistics, but line 12/13 in chartjs-chart-box-and-violin-plot/src/data.js overrides those calculations by settings whiskerMin & whiskerMax to boxplot.q1 - irq and boxplot.q3 + iqr respectively.

See the following code pen where this behavior is demonstrated, the min and max are being overridden in lines 12 & 13. 
https://codepen.io/gkemp94/pen/PxvraY?editors=0010 

Thanks again for taking a look at this. 
George
