### ISSUE TITLE
Bug: Violinchart with just one number crashes browser

### ISSUE THREAD

**Issue by Chris1234567899** [datavisyn/chartjs-chart-box-and-violin-plot#39]
Trying to draw a violin chart with just one single number in the data, crashes the browser. Tried in latest chrome.

**Comment by sluger** [comment]
hi @Chris1234567899, can you please provide an example similar to this codepen: https://codepen.io/sluger/pen/LvQyyG

**Comment by Chris1234567899** [comment]
Just use the codepen you have linked and replace 

> data: [
>       randomValues(100, 0, 100)
>     ]

with

> data: [
>       randomValues(1, 0, 100)
>     ]

Chrome will crash (without any error message). Maybe something is running to infinity, divided by 0 or smth alike. I could not save it as a new codepen, because everytime it loads, it crashes because of the bug ;-)

**Comment by sluger** [comment]
I provide a fix that the chart does not break anymore. 

Nonetheless, why would you try to draw a violin plot out of an array of one element containing only a single data point. Because of a single data point, the scale computed has no range, so the point can't be drawn easily. Or at least, I think the effort to implement this is too high for the benefit you gain.

**Comment by Chris1234567899** [comment]
Thanks, while I agree that it is pointless to draw a chart with just one number, this can happen, when the data is for example coming from some api. In such a case I think it's ok to not draw the chart and throw a warning, but it should not freeze or crash the entire browser.
