### ISSUE TITLE
Boxplot is not compatible with other plot types when mixing

### ISSUE THREAD

**Issue by chankiyu22** [datavisyn/chartjs-chart-box-and-violin-plot#42]
### Description

When trying to mix box plot with other plot types (refs https://www.chartjs.org/docs/latest/charts/mixed.html), one of them cannot be displayed correctly.

### Steps to reproduce

https://codepen.io/chankiyu22/pen/VNGGGz

### Expected Result

Both plots should be displayed correctly

**Comment by nickrussler** [comment]
This would be especially interesting for combining with scatter plots, e.g. for hovarable items and outliers.

**Comment by sgratzl** [comment]
I played around with it a bit. In the latest version, one needs to specify the max of the yAxis since the current implementation has  not a fallback for not boxplot values. 

so I added: 
```
      'yAxes': [{
        ticks: {
          max: 60
        }
      }]
```

![image](https://user-images.githubusercontent.com/4129778/60393071-dd10cc80-9b52-11e9-9592-2ff050d61c1b.png)


the other way around (line as base) doesn't seem to work, not even when just using a regular bar chart (so line + bar)

**Comment by sgratzl** [comment]
> This would be especially interesting for combining with scatter plots, e.g. for hovarable items and outliers.

I started implementing a approach to provide tooltips for outliers. see https://github.com/datavisyn/chartjs-chart-box-and-violin-plot/pull/52

**Comment by sgratzl** [comment]
closing for now with an improved compatibilty
