### ISSUE TITLE
does it support server side rendering ? 

### ISSUE THREAD

**Issue by bakkiung** [datavisyn/chartjs-chart-box-and-violin-plot#75]

**Comment by sgratzl** [comment]
this is just a plugin of chart.js so the chartj.js community would be a better place to ask this question. Do you want to create images on the server side and export it to e.g. a PNG or do you mean to render the canvas with the image on the server before sending it to the client?

the first case, take a look at https://github.com/Automattic/node-canvas 
second case: I don't know any way to render an canvas image on the server and deliver the resulting canvas to the client. The canvas is just a place to render things but the rendering has to be done on the client side. If you really want an immediate response you could render the image on the server side in a png and overlay the canvas with it till you rendered the interactive version on the client. Tho, I'm not sure whether you get any performance improvements. If you are worried about the data amount to transfer you could give this plugin just aggregates (so the boxplot data) directly instead of the raw data.

**Comment by sgratzl** [comment]
does this information help you, if so, please close this issue

**Comment by Perlkonig** [comment]
For the record, I use [ChartjsNodeCanvas](https://github.com/SeanSobey/ChartjsNodeCanvas) to do server-side rendering, and [this plugin works just fine in that context](https://github.com/SeanSobey/ChartjsNodeCanvas/issues/44).
